---
# The Deployment (the Pod recipe)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: todoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.9 # A specific, stable version
        ports:
        - containerPort: 3306
        env:
        - name: MARIADB_ROOT_PASSWORD
          value: "labpassword"
        - name: MARIADB_DATABASE
          value: "todoapp"
        volumeMounts:
        - name: mariadb-storage
          mountPath: /var/lib/mysql # Where MariaDB stores its data
      volumes:
      - name: mariadb-storage
        persistentVolumeClaim:
          claimName: mariadb-pvc # This connects to our PVC

---
# The Service (the internal network name)
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: todoapp
spec:
  selector:
    app: mariadb
  ports:
  - port: 3306
    targetPort: 3306
