---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: todoapp
spec:
  replicas: 2 # Let's run two copies for high availability!
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      # --- ADD THIS BLOCK ---
      nodeSelector:
        kubernetes.io/hostname: k3s-n1
      # --- END BLOCK ---
      containers:
      - name: flask
        image: python-todo-app:latest # NOTE: This image doesn't exist... yet
        imagePullPolicy: IfNotPresent  # <--- ADD THIS LINE
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: "mariadb" # The DNS name of our DB service
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "labpassword"
        - name: DB_NAME
          value: "todoapp"
