apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
  namespace: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: todo-app
          # --- THIS IS THE LINE WE WILL AUTOMATE ---
          image: "ghcr.io/dusansvoboda/python-todo-app:7912eaf5d8c90151ed7681c937015d4aa18ee038"
          # ----------------------------------------
          ports:
            - containerPort: 5000
